/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Clause {
  'title' : string,
  'content' : string,
  'explanation' : string,
}
export interface DateInfo { 'date' : string, 'purpose' : string }
export type Domain = { 'legal' : null } |
  { 'general' : null } |
  { 'medical' : null };
export type EntryType = { 'other' : null } |
  { 'exam' : null } |
  { 'deadline' : null } |
  { 'classes' : null } |
  { 'studySession' : null };
export type ExternalBlob = Uint8Array;
export interface LegalAnalysis {
  'owner' : Principal,
  'rights' : Array<Right>,
  'clauses' : Array<Clause>,
  'summary' : string,
  'obligations' : Array<Obligation>,
  'dates' : Array<DateInfo>,
  'parties' : Array<Party>,
}
export interface MedicalReport {
  'id' : string,
  'domain' : Domain,
  'owner' : Principal,
  'file' : ExternalBlob,
  'isAnalysed' : boolean,
  'uploadTimestamp' : bigint,
  'analysis' : [] | [string],
}
export interface Note {
  'id' : string,
  'title' : string,
  'content' : string,
  'domain' : Domain,
  'owner' : Principal,
  'isArchived' : boolean,
  'timestamp' : bigint,
}
export interface Obligation { 'description' : string, 'party' : string }
export interface Party { 'name' : string, 'role' : string }
export interface Question {
  'correctAnswer' : string,
  'questionText' : string,
  'options' : Array<string>,
}
export interface Quiz {
  'id' : string,
  'title' : string,
  'owner' : Principal,
  'creationTimestamp' : bigint,
  'questions' : Array<Question>,
}
export interface RevisionReminder {
  'id' : bigint,
  'topic' : string,
  'active' : boolean,
  'owner' : Principal,
  'timesRevised' : bigint,
  'nextRevision' : string,
}
export interface Right { 'description' : string, 'party' : string }
export interface TimetableEntry {
  'id' : bigint,
  'startTime' : string,
  'title' : string,
  'entryType' : EntryType,
  'endTime' : string,
  'owner' : Principal,
  'recurring' : boolean,
  'location' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNote' : ActorMethod<[string, string, string], string>,
  'createRevisionReminder' : ActorMethod<[string, bigint, string], bigint>,
  'createTimetableEntry' : ActorMethod<
    [string, string, string, string, string, boolean],
    bigint
  >,
  'deactivateReminder' : ActorMethod<[bigint], undefined>,
  'deleteNote' : ActorMethod<[string], undefined>,
  'deleteTimetableEntry' : ActorMethod<[bigint], undefined>,
  'editNote' : ActorMethod<[string, string, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLegalAnalysis' : ActorMethod<[string], LegalAnalysis>,
  'getMedicalReport' : ActorMethod<[string], MedicalReport>,
  'getMedicalReportsCountForCaller' : ActorMethod<[], bigint>,
  'getNote' : ActorMethod<[string], Note>,
  'getNotesCountForCaller' : ActorMethod<[], bigint>,
  'getQuiz' : ActorMethod<[string], Quiz>,
  'getUserNotes' : ActorMethod<[], Array<Note>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserQuizzes' : ActorMethod<[], Array<Quiz>>,
  'getUserReminders' : ActorMethod<[], Array<RevisionReminder>>,
  'getUserReports' : ActorMethod<[], Array<MedicalReport>>,
  'getUserTimetableEntries' : ActorMethod<[], Array<TimetableEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveAnalysis' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLegalAnalysis' : ActorMethod<
    [
      string,
      Array<Clause>,
      Array<Obligation>,
      Array<Right>,
      Array<Party>,
      Array<DateInfo>,
      string,
    ],
    undefined
  >,
  'saveQuiz' : ActorMethod<[string, Array<Question>], string>,
  'updateReminder' : ActorMethod<[bigint, bigint, string], undefined>,
  'uploadMedicalReport' : ActorMethod<[ExternalBlob, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];