/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Right = IDL.Record({
  'description' : IDL.Text,
  'party' : IDL.Text,
});
export const Clause = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'explanation' : IDL.Text,
});
export const Obligation = IDL.Record({
  'description' : IDL.Text,
  'party' : IDL.Text,
});
export const DateInfo = IDL.Record({ 'date' : IDL.Text, 'purpose' : IDL.Text });
export const Party = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const LegalAnalysis = IDL.Record({
  'owner' : IDL.Principal,
  'rights' : IDL.Vec(Right),
  'clauses' : IDL.Vec(Clause),
  'summary' : IDL.Text,
  'obligations' : IDL.Vec(Obligation),
  'dates' : IDL.Vec(DateInfo),
  'parties' : IDL.Vec(Party),
});
export const Domain = IDL.Variant({
  'legal' : IDL.Null,
  'general' : IDL.Null,
  'medical' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MedicalReport = IDL.Record({
  'id' : IDL.Text,
  'domain' : Domain,
  'owner' : IDL.Principal,
  'file' : ExternalBlob,
  'isAnalysed' : IDL.Bool,
  'uploadTimestamp' : IDL.Int,
  'analysis' : IDL.Opt(IDL.Text),
});
export const Note = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'domain' : Domain,
  'owner' : IDL.Principal,
  'isArchived' : IDL.Bool,
  'timestamp' : IDL.Int,
});
export const Question = IDL.Record({
  'correctAnswer' : IDL.Text,
  'questionText' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Quiz = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'creationTimestamp' : IDL.Int,
  'questions' : IDL.Vec(Question),
});
export const RevisionReminder = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'active' : IDL.Bool,
  'owner' : IDL.Principal,
  'timesRevised' : IDL.Nat,
  'nextRevision' : IDL.Text,
});
export const EntryType = IDL.Variant({
  'other' : IDL.Null,
  'exam' : IDL.Null,
  'deadline' : IDL.Null,
  'classes' : IDL.Null,
  'studySession' : IDL.Null,
});
export const TimetableEntry = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'title' : IDL.Text,
  'entryType' : EntryType,
  'endTime' : IDL.Text,
  'owner' : IDL.Principal,
  'recurring' : IDL.Bool,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createRevisionReminder' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createTimetableEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'deactivateReminder' : IDL.Func([IDL.Nat], [], []),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'deleteTimetableEntry' : IDL.Func([IDL.Nat], [], []),
  'editNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLegalAnalysis' : IDL.Func([IDL.Text], [LegalAnalysis], ['query']),
  'getMedicalReport' : IDL.Func([IDL.Text], [MedicalReport], ['query']),
  'getMedicalReportsCountForCaller' : IDL.Func([], [IDL.Nat], ['query']),
  'getNote' : IDL.Func([IDL.Text], [Note], ['query']),
  'getNotesCountForCaller' : IDL.Func([], [IDL.Nat], ['query']),
  'getQuiz' : IDL.Func([IDL.Text], [Quiz], ['query']),
  'getUserNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
  'getUserReminders' : IDL.Func([], [IDL.Vec(RevisionReminder)], ['query']),
  'getUserReports' : IDL.Func([], [IDL.Vec(MedicalReport)], ['query']),
  'getUserTimetableEntries' : IDL.Func(
      [],
      [IDL.Vec(TimetableEntry)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAnalysis' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveLegalAnalysis' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(Clause),
        IDL.Vec(Obligation),
        IDL.Vec(Right),
        IDL.Vec(Party),
        IDL.Vec(DateInfo),
        IDL.Text,
      ],
      [],
      [],
    ),
  'saveQuiz' : IDL.Func([IDL.Text, IDL.Vec(Question)], [IDL.Text], []),
  'updateReminder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'uploadMedicalReport' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Right = IDL.Record({ 'description' : IDL.Text, 'party' : IDL.Text });
  const Clause = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'explanation' : IDL.Text,
  });
  const Obligation = IDL.Record({
    'description' : IDL.Text,
    'party' : IDL.Text,
  });
  const DateInfo = IDL.Record({ 'date' : IDL.Text, 'purpose' : IDL.Text });
  const Party = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const LegalAnalysis = IDL.Record({
    'owner' : IDL.Principal,
    'rights' : IDL.Vec(Right),
    'clauses' : IDL.Vec(Clause),
    'summary' : IDL.Text,
    'obligations' : IDL.Vec(Obligation),
    'dates' : IDL.Vec(DateInfo),
    'parties' : IDL.Vec(Party),
  });
  const Domain = IDL.Variant({
    'legal' : IDL.Null,
    'general' : IDL.Null,
    'medical' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MedicalReport = IDL.Record({
    'id' : IDL.Text,
    'domain' : Domain,
    'owner' : IDL.Principal,
    'file' : ExternalBlob,
    'isAnalysed' : IDL.Bool,
    'uploadTimestamp' : IDL.Int,
    'analysis' : IDL.Opt(IDL.Text),
  });
  const Note = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'domain' : Domain,
    'owner' : IDL.Principal,
    'isArchived' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  const Question = IDL.Record({
    'correctAnswer' : IDL.Text,
    'questionText' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Quiz = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'creationTimestamp' : IDL.Int,
    'questions' : IDL.Vec(Question),
  });
  const RevisionReminder = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'active' : IDL.Bool,
    'owner' : IDL.Principal,
    'timesRevised' : IDL.Nat,
    'nextRevision' : IDL.Text,
  });
  const EntryType = IDL.Variant({
    'other' : IDL.Null,
    'exam' : IDL.Null,
    'deadline' : IDL.Null,
    'classes' : IDL.Null,
    'studySession' : IDL.Null,
  });
  const TimetableEntry = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'title' : IDL.Text,
    'entryType' : EntryType,
    'endTime' : IDL.Text,
    'owner' : IDL.Principal,
    'recurring' : IDL.Bool,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'createRevisionReminder' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createTimetableEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'deactivateReminder' : IDL.Func([IDL.Nat], [], []),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'deleteTimetableEntry' : IDL.Func([IDL.Nat], [], []),
    'editNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLegalAnalysis' : IDL.Func([IDL.Text], [LegalAnalysis], ['query']),
    'getMedicalReport' : IDL.Func([IDL.Text], [MedicalReport], ['query']),
    'getMedicalReportsCountForCaller' : IDL.Func([], [IDL.Nat], ['query']),
    'getNote' : IDL.Func([IDL.Text], [Note], ['query']),
    'getNotesCountForCaller' : IDL.Func([], [IDL.Nat], ['query']),
    'getQuiz' : IDL.Func([IDL.Text], [Quiz], ['query']),
    'getUserNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
    'getUserReminders' : IDL.Func([], [IDL.Vec(RevisionReminder)], ['query']),
    'getUserReports' : IDL.Func([], [IDL.Vec(MedicalReport)], ['query']),
    'getUserTimetableEntries' : IDL.Func(
        [],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAnalysis' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLegalAnalysis' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(Clause),
          IDL.Vec(Obligation),
          IDL.Vec(Right),
          IDL.Vec(Party),
          IDL.Vec(DateInfo),
          IDL.Text,
        ],
        [],
        [],
      ),
    'saveQuiz' : IDL.Func([IDL.Text, IDL.Vec(Question)], [IDL.Text], []),
    'updateReminder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'uploadMedicalReport' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };